version: '3'
services:
  www:
    container_name: graphql_app
    build: 
      context: ./www
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data:/data/db

volumes:
  data: